// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Servicio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EstructuraCentralizadaClient is the client API for EstructuraCentralizada service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EstructuraCentralizadaClient interface {
	Hello(ctx context.Context, in *T, opts ...grpc.CallOption) (*T, error)
}

type estructuraCentralizadaClient struct {
	cc grpc.ClientConnInterface
}

func NewEstructuraCentralizadaClient(cc grpc.ClientConnInterface) EstructuraCentralizadaClient {
	return &estructuraCentralizadaClient{cc}
}

func (c *estructuraCentralizadaClient) Hello(ctx context.Context, in *T, opts ...grpc.CallOption) (*T, error) {
	out := new(T)
	err := c.cc.Invoke(ctx, "/paquete.estructura_centralizada/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstructuraCentralizadaServer is the server API for EstructuraCentralizada service.
// All implementations must embed UnimplementedEstructuraCentralizadaServer
// for forward compatibility
type EstructuraCentralizadaServer interface {
	Hello(context.Context, *T) (*T, error)
	mustEmbedUnimplementedEstructuraCentralizadaServer()
}

// UnimplementedEstructuraCentralizadaServer must be embedded to have forward compatible implementations.
type UnimplementedEstructuraCentralizadaServer struct {
}

func (UnimplementedEstructuraCentralizadaServer) Hello(context.Context, *T) (*T, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedEstructuraCentralizadaServer) mustEmbedUnimplementedEstructuraCentralizadaServer() {
}

// UnsafeEstructuraCentralizadaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EstructuraCentralizadaServer will
// result in compilation errors.
type UnsafeEstructuraCentralizadaServer interface {
	mustEmbedUnimplementedEstructuraCentralizadaServer()
}

func RegisterEstructuraCentralizadaServer(s grpc.ServiceRegistrar, srv EstructuraCentralizadaServer) {
	s.RegisterService(&_EstructuraCentralizada_serviceDesc, srv)
}

func _EstructuraCentralizada_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(T)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraCentralizadaServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_centralizada/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraCentralizadaServer).Hello(ctx, req.(*T))
	}
	return interceptor(ctx, in, info, handler)
}

var _EstructuraCentralizada_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paquete.estructura_centralizada",
	HandlerType: (*EstructuraCentralizadaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _EstructuraCentralizada_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Servicio/paquete.proto",
}
