// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Servicio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EstructuraDistribuidaClient is the client API for EstructuraDistribuida service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EstructuraDistribuidaClient interface {
	Subir(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*UploadStatus, error)
	EnviarPropuesta(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Respuesta, error)
	VerificarEstadoServidor(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error)
	EnviarChunk(ctx context.Context, in *ChunkSendToServer, opts ...grpc.CallOption) (*Mensaje, error)
	BajarArchivo(ctx context.Context, in *BookToDownload, opts ...grpc.CallOption) (*ListChunk, error)
	BajarChunk(ctx context.Context, in *ChunkDes, opts ...grpc.CallOption) (*ChunkBook, error)
	ObtenerLibrosDisponibles(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Books, error)
	PedirRecurso(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error)
	LiberarRecurso(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error)
	WriteLogs(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Mensaje, error)
}

type estructuraDistribuidaClient struct {
	cc grpc.ClientConnInterface
}

func NewEstructuraDistribuidaClient(cc grpc.ClientConnInterface) EstructuraDistribuidaClient {
	return &estructuraDistribuidaClient{cc}
}

func (c *estructuraDistribuidaClient) Subir(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*UploadStatus, error) {
	out := new(UploadStatus)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/Subir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) EnviarPropuesta(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/EnviarPropuesta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) VerificarEstadoServidor(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/VerificarEstadoServidor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) EnviarChunk(ctx context.Context, in *ChunkSendToServer, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/EnviarChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) BajarArchivo(ctx context.Context, in *BookToDownload, opts ...grpc.CallOption) (*ListChunk, error) {
	out := new(ListChunk)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/BajarArchivo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) BajarChunk(ctx context.Context, in *ChunkDes, opts ...grpc.CallOption) (*ChunkBook, error) {
	out := new(ChunkBook)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/BajarChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) ObtenerLibrosDisponibles(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Books, error) {
	out := new(Books)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/ObtenerLibrosDisponibles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) PedirRecurso(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/PedirRecurso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) LiberarRecurso(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/LiberarRecurso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estructuraDistribuidaClient) WriteLogs(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Mensaje, error) {
	out := new(Mensaje)
	err := c.cc.Invoke(ctx, "/paquete.estructura_distribuida/WriteLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstructuraDistribuidaServer is the server API for EstructuraDistribuida service.
// All implementations must embed UnimplementedEstructuraDistribuidaServer
// for forward compatibility
type EstructuraDistribuidaServer interface {
	Subir(context.Context, *Chunk) (*UploadStatus, error)
	EnviarPropuesta(context.Context, *Propuesta) (*Respuesta, error)
	VerificarEstadoServidor(context.Context, *Mensaje) (*Mensaje, error)
	EnviarChunk(context.Context, *ChunkSendToServer) (*Mensaje, error)
	BajarArchivo(context.Context, *BookToDownload) (*ListChunk, error)
	BajarChunk(context.Context, *ChunkDes) (*ChunkBook, error)
	ObtenerLibrosDisponibles(context.Context, *Mensaje) (*Books, error)
	PedirRecurso(context.Context, *Mensaje) (*Mensaje, error)
	LiberarRecurso(context.Context, *Mensaje) (*Mensaje, error)
	WriteLogs(context.Context, *Propuesta) (*Mensaje, error)
	mustEmbedUnimplementedEstructuraDistribuidaServer()
}

// UnimplementedEstructuraDistribuidaServer must be embedded to have forward compatible implementations.
type UnimplementedEstructuraDistribuidaServer struct {
}

func (UnimplementedEstructuraDistribuidaServer) Subir(context.Context, *Chunk) (*UploadStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subir not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) EnviarPropuesta(context.Context, *Propuesta) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarPropuesta not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) VerificarEstadoServidor(context.Context, *Mensaje) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificarEstadoServidor not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) EnviarChunk(context.Context, *ChunkSendToServer) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarChunk not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) BajarArchivo(context.Context, *BookToDownload) (*ListChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BajarArchivo not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) BajarChunk(context.Context, *ChunkDes) (*ChunkBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BajarChunk not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) ObtenerLibrosDisponibles(context.Context, *Mensaje) (*Books, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerLibrosDisponibles not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) PedirRecurso(context.Context, *Mensaje) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PedirRecurso not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) LiberarRecurso(context.Context, *Mensaje) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiberarRecurso not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) WriteLogs(context.Context, *Propuesta) (*Mensaje, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteLogs not implemented")
}
func (UnimplementedEstructuraDistribuidaServer) mustEmbedUnimplementedEstructuraDistribuidaServer() {}

// UnsafeEstructuraDistribuidaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EstructuraDistribuidaServer will
// result in compilation errors.
type UnsafeEstructuraDistribuidaServer interface {
	mustEmbedUnimplementedEstructuraDistribuidaServer()
}

func RegisterEstructuraDistribuidaServer(s *grpc.Server, srv EstructuraDistribuidaServer) {
	s.RegisterService(&_EstructuraDistribuida_serviceDesc, srv)
}

func _EstructuraDistribuida_Subir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).Subir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/Subir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).Subir(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_EnviarPropuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Propuesta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).EnviarPropuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/EnviarPropuesta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).EnviarPropuesta(ctx, req.(*Propuesta))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_VerificarEstadoServidor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).VerificarEstadoServidor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/VerificarEstadoServidor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).VerificarEstadoServidor(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_EnviarChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkSendToServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).EnviarChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/EnviarChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).EnviarChunk(ctx, req.(*ChunkSendToServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_BajarArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookToDownload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).BajarArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/BajarArchivo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).BajarArchivo(ctx, req.(*BookToDownload))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_BajarChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkDes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).BajarChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/BajarChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).BajarChunk(ctx, req.(*ChunkDes))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_ObtenerLibrosDisponibles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).ObtenerLibrosDisponibles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/ObtenerLibrosDisponibles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).ObtenerLibrosDisponibles(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_PedirRecurso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).PedirRecurso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/PedirRecurso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).PedirRecurso(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_LiberarRecurso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).LiberarRecurso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/LiberarRecurso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).LiberarRecurso(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

func _EstructuraDistribuida_WriteLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Propuesta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstructuraDistribuidaServer).WriteLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paquete.estructura_distribuida/WriteLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstructuraDistribuidaServer).WriteLogs(ctx, req.(*Propuesta))
	}
	return interceptor(ctx, in, info, handler)
}

var _EstructuraDistribuida_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paquete.estructura_distribuida",
	HandlerType: (*EstructuraDistribuidaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subir",
			Handler:    _EstructuraDistribuida_Subir_Handler,
		},
		{
			MethodName: "EnviarPropuesta",
			Handler:    _EstructuraDistribuida_EnviarPropuesta_Handler,
		},
		{
			MethodName: "VerificarEstadoServidor",
			Handler:    _EstructuraDistribuida_VerificarEstadoServidor_Handler,
		},
		{
			MethodName: "EnviarChunk",
			Handler:    _EstructuraDistribuida_EnviarChunk_Handler,
		},
		{
			MethodName: "BajarArchivo",
			Handler:    _EstructuraDistribuida_BajarArchivo_Handler,
		},
		{
			MethodName: "BajarChunk",
			Handler:    _EstructuraDistribuida_BajarChunk_Handler,
		},
		{
			MethodName: "ObtenerLibrosDisponibles",
			Handler:    _EstructuraDistribuida_ObtenerLibrosDisponibles_Handler,
		},
		{
			MethodName: "PedirRecurso",
			Handler:    _EstructuraDistribuida_PedirRecurso_Handler,
		},
		{
			MethodName: "LiberarRecurso",
			Handler:    _EstructuraDistribuida_LiberarRecurso_Handler,
		},
		{
			MethodName: "WriteLogs",
			Handler:    _EstructuraDistribuida_WriteLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paquete.proto",
}
