hello:
	echo "Hello nameNode"
build:
	go build -o bin/main dataNode2.go localhost:50051 localhost:50052 localhost:50053 localhost:50055
run:
	go run dataNode2.go localhost:50051 localhost:50052 localhost:50053 localhost:50055
	
